import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';

import TopSideBar from '@/components/TopSidebar';
import BottomSideBar from '@/components/BottomSideBar';
import LeftSidebar from '@/components/LeftSideBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Face Recognition',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang='en'>
        <body className={inter.className}>
          <TopSideBar />

          <main className='flex flex-row'>
            <LeftSidebar />
            <section className='main-container'>
              <div className='w-full max-w-6xl'>{children}</div>
            </section>
            {/* @ts-ignore */}
          </main>

          <BottomSideBar />
        </body>
      </html>
    </ClerkProvider>
  );
}
